myListBadRange2.chpl:8: In function 'main':
myListBadRange2.chpl:16: error: cannot call `get()` on a Python list with a range with stride other than 1
